run:
	g++ -c -o Wielomian.o Wielomian.cpp
	g++ -o WielomianTest.o WielomianTest.cpp Wielomian.cpp
	./WielomianTest.o
	@echo 
	@make clean

clean:                                                     
	rm -f *.o  *~ *.a *.so *.x core core* a.out; rm -rf ${LIB_DIR}