run:
	g++ -c -o listaTablicowa.o listaTablicowa.cpp
	g++ -o ListaTest.o ListaTest.cpp
	./ListaTest.o

clean:                                                     
	rm -f *.o  *~ *.a *.so *.x core core* a.out; rm -rf ${LIB_DIR}